name: postfix-mta-sts-resolver
version: '0.8.2'
summary: Policy-server for Postfix which handles MTA-STS resolving
description: |
  Daemon which provides TLS client policy for Postfix via socketmap, 
  according to domain MTA-STS policy.
confinement: devmode
base: core18

parts:
  extras:
    plugin: python
    python-version: python3
    python-packages:
      - "aiosqlite>=0.10.0"
      - "aioredis>=1.2.0"
  postfix-mta-sts-resolver:
    plugin: python
    python-version: python3
    source: .

apps:
  daemon:
    command: bin/mta-sts-daemon
    plugs:
      - network
      - network-bind
  query:
    command: bin/mta-sts-query
    plugs:
      - network
